package com.tripletriad.server

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * The one-time codes, measured against the RFC's own numbers.
 *
 * ### Why this file is the reason `Totp` is allowed to exist
 *
 * `Totp.kt` argues for a hand-written implementation over a dependency, and the argument is not
 * "forty lines is easy" — it is that **RFC 6238 publishes test vectors**, so the implementation can
 * be *checked* rather than trusted. That claim is worth exactly as much as this file, and without
 * it the trade would have been the wrong way round: a library nobody verified still beats
 * arithmetic nobody verified.
 *
 * So the six vectors below are not a smoke test of an interface. They are the argument, and they
 * are copied from Appendix B rather than generated by the code they check — which is the only way
 * round that proves anything.
 *
 * ### What is deliberately not pinned
 *
 * [Totp.issueSecret]'s output, which is random by definition. What is checked about it is that a
 * secret this code generates is one this code can then verify against, because a base32 encoder
 * that disagrees with its own decoder would pass every vector above and fail every real enrolment.
 */
class TotpTest {

    /**
     * All six of RFC 6238 Appendix B's SHA-1 vectors, at six digits.
     *
     * The appendix prints eight-digit codes; six digits is the same dynamic truncation modulo a
     * smaller number, so the expected value is the printed one's last six. Both the seed and the
     * times are the RFC's, including `20000000000` — past 2^31 seconds, which is the vector that
     * catches an implementation that put the counter in an `Int`.
     */
    @Test
    fun theRfcsOwnVectorsPass() {
        val vectors = listOf(
            59L to "287082",
            1_111_111_109L to "081804",
            1_111_111_111L to "050471",
            1_234_567_890L to "005924",
            2_000_000_000L to "279037",
            20_000_000_000L to "353130",
        )

        for ((seconds, expected) in vectors) {
            val step = Totp.stepAt(seconds * MILLIS_PER_SECOND)
            assertEquals(expected, Totp.code(RFC_SECRET, step), "at T=$seconds")
        }
    }

    /** The RFC's seed is ASCII; this is the base32 of it, and the two have to agree. */
    @Test
    fun theSeedIsTheAsciiStringTheRfcPrints() {
        val bytes = RFC_SEED.toByteArray(Charsets.US_ASCII)
        assertEquals(SEED_BYTES, bytes.size)
        // Base32 is not reachable from a test — it is `Totp`'s private business — so the agreement
        // is checked the way a caller would notice it: the secret decodes to the seed the vectors
        // were computed from, or the codes above would not have matched.
        assertEquals(RFC_SECRET.length, ((bytes.size * BITS_PER_BYTE) + 4) / BITS_PER_CHARACTER)
    }

    /**
     * A code from the neighbouring step is accepted, and one two steps away is not.
     *
     * This is the clock-skew window, and it is a security parameter rather than a convenience:
     * every step of tolerance widens the target a guesser is shooting at. One either side is the
     * RFC's own recommendation and it is what [Totp] implements — the test exists so that widening
     * it later is a deliberate edit to a number *and* to an assertion, not a quiet change.
     */
    @Test
    fun oneStepOfSkewIsForgivenAndTwoIsNot() {
        val now = 1_700_000_000_000L
        val current = Totp.stepAt(now)

        for (offset in -1..1) {
            val code = Totp.code(RFC_SECRET, current + offset)
            assertEquals(
                current + offset,
                Totp.matchingStep(RFC_SECRET, code, now),
                "a code $offset steps away should be accepted, and identified as its own step",
            )
        }

        assertNull(Totp.matchingStep(RFC_SECRET, Totp.code(RFC_SECRET, current - 2), now))
        assertNull(Totp.matchingStep(RFC_SECRET, Totp.code(RFC_SECRET, current + 2), now))
    }

    /**
     * The step a code matches is reported, not merely that it matched.
     *
     * `AdminStore.recordStep` refuses a step it has already seen, which is what makes a code
     * single-use — and it can only do that if the verifier says *which* step was satisfied. A
     * boolean here would have made replay prevention impossible to write correctly.
     */
    @Test
    fun theMatchingStepIsTheOneTheCodeWasComputedFrom() {
        val secret = Totp.issueSecret()
        val step = Totp.stepAt(1_600_000_000_000L)

        assertEquals(step, Totp.matchingStep(secret, Totp.code(secret, step), step * STEP_MILLIS))
    }

    /** A freshly issued secret verifies against itself: the encoder and the decoder agree. */
    @Test
    fun aFreshSecretRoundTripsThroughACode() {
        val now = System.currentTimeMillis()
        val secret = Totp.issueSecret()

        val code = Totp.code(secret, Totp.stepAt(now))

        assertEquals(Totp.DIGITS, code.length)
        assertTrue(code.all { it.isDigit() }, "a code is digits only")
        assertNotNull(Totp.matchingStep(secret, code, now))
    }

    /** Two secrets are two secrets. Trivial, and the thing a broken CSPRNG would fail. */
    @Test
    fun twoIssuedSecretsDiffer() {
        assertTrue(Totp.issueSecret() != Totp.issueSecret())
    }

    /**
     * An authenticator app's spacing and case are accepted, because that is what people type.
     *
     * Authenticators print a secret in groups of four and some accept it back in lower case, so a
     * strict decoder would refuse a key the operator copied correctly. The tolerance is in the
     * decoder rather than at the route, so every caller gets it.
     */
    @Test
    fun aSecretIsTheSameSecretWithSpacesAndInLowerCase() {
        val step = Totp.stepAt(1_500_000_000_000L)
        val expected = Totp.code(RFC_SECRET, step)

        assertEquals(expected, Totp.code(RFC_SECRET.lowercase(), step))
        assertEquals(expected, Totp.code(RFC_SECRET.chunked(4).joinToString(" "), step))
        assertEquals(expected, Totp.code("$RFC_SECRET======", step))
    }

    /**
     * A secret that is not base32 produces no code and matches nothing — it does not throw.
     *
     * `admins.totp_secret` is a `text` column, so a hand-edited row is a shape this has to survive.
     * The right answer is a refused sign-in rather than a 500: a corrupt secret is a reason nobody
     * can get in, not a reason to tell the caller the row exists and is broken.
     */
    @Test
    fun aSecretThatIsNotBase32RefusesRatherThanThrows() {
        val now = System.currentTimeMillis()

        for (broken in listOf("", "not base32!", "AAAA1AAAA", "0189")) {
            assertEquals("", Totp.code(broken, Totp.stepAt(now)), "code from <$broken>")
            assertNull(Totp.matchingStep(broken, "000000", now), "match against <$broken>")
        }
    }

    /**
     * Anything that is not exactly [Totp.DIGITS] digits is refused before any arithmetic.
     *
     * Including the empty string, which is what an absent field deserialises to on a form somebody
     * submitted early — and which must not be treated as a code that happens to be wrong, because a
     * comparison against a truncated value is the shape a prefix match sneaks in through.
     */
    @Test
    fun aCodeOfTheWrongLengthIsRefused() {
        val now = System.currentTimeMillis()
        val valid = Totp.code(RFC_SECRET, Totp.stepAt(now))

        for (typed in listOf("", " ", valid.take(Totp.DIGITS - 1), valid + "0", "abcdef")) {
            assertNull(Totp.matchingStep(RFC_SECRET, typed, now), "<$typed> should not match")
        }
    }

    /**
     * The `otpauth://` URI carries the issuer twice, which is what authenticator apps read.
     *
     * The label is `Issuer:account` and the `issuer` parameter repeats it; apps disagree about
     * which they show, and one without the other shows a nameless entry in somebody's authenticator
     * list. The secret appears in it because that is the point of it — this string is as secret as
     * the key.
     */
    @Test
    fun theUriNamesTheIssuerTheAccountAndTheKey() {
        val uri = Totp.uri("Triple Triad", "ada", RFC_SECRET)

        assertTrue(uri.startsWith("otpauth://totp/"), uri)
        assertTrue(uri.contains("Triple%20Triad:ada"), uri)
        assertTrue(uri.contains("secret=$RFC_SECRET"), uri)
        assertTrue(uri.contains("issuer=Triple%20Triad"), uri)
        assertTrue(uri.contains("digits=${Totp.DIGITS}"), uri)
        assertTrue(uri.contains("period=${Totp.STEP_SECONDS}"), uri)
    }

    /** RFC 6238 Appendix B's seed, in the form the appendix prints it. */
    private companion object {
        const val RFC_SEED = "12345678901234567890"

        /** The same twenty bytes, base32 — which is the form an authenticator is given. */
        const val RFC_SECRET = "GEZDGNBVGY3TQOJQGEZDGNBVGY3TQOJQ"

        const val SEED_BYTES = 20
        const val BITS_PER_BYTE = 8
        const val BITS_PER_CHARACTER = 5
        const val MILLIS_PER_SECOND = 1_000L
        const val STEP_MILLIS = 30_000L
    }
}
